name-template: '$NEXT_PATCH_VERSION'
tag-template: '$NEXT_PATCH_VERSION'
categories:
  - title: '### Features'
    labels: 'feat'
  - title: '### Fixes'
    labels: 'fix'
  - title: '### Dependencies'
    label: 'chore'
change-template: '- $TITLE [#$NUMBER]'
template: |
  $CHANGES
