# Config for https://github.com/toolmantim/release-drafter
name-template: '$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

categories:
  - title: 'Bug Fixes'
    label: 'bug'
  - title: 'Enhancements'
    label: 'enhancement'

template: |
  ## Changes
  $CHANGES